<?php declare(strict_types = 1);

return PHPStan\Cache\CacheItem::__set_state(array(
   'variableKey' => '0.4.8',
   'data' => 'O:42:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocNode":1:{s:8:"children";a:10:{i:0;O:46:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTextNode":1:{s:4:"text";s:31:"Gets all available permissions.";}i:1;O:46:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTextNode":1:{s:4:"text";s:0:"";}i:2;O:45:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTagNode":2:{s:4:"name";s:7:"@return";s:5:"value";O:50:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\ReturnTagValueNode":2:{s:4:"type";O:48:"PHPStan\\PhpDocParser\\Ast\\Type\\IdentifierTypeNode":1:{s:4:"name";s:5:"array";}s:11:"description";s:0:"";}}i:3;O:46:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTextNode":1:{s:4:"text";s:124:"An array whose keys are permission names and whose corresponding values
are arrays containing the following key-value pairs:";}i:4;O:46:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTextNode":1:{s:4:"text";s:170:"- title: The human-readable name of the permission, to be shown on the
permission administration page. This should be wrapped in the t()
function so it can be translated.";}i:5;O:46:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTextNode":1:{s:4:"text";s:136:"- description: (optional) A description of what the permission does. This
should be wrapped in the t() function so it can be translated.";}i:6;O:46:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTextNode":1:{s:4:"text";s:271:"- restrict access: (optional) A boolean which can be set to TRUE to
indicate that site administrators should restrict access to this
permission to trusted users. This should be used for permissions that
have inherent security risks across a variety of potential use cases";}i:7;O:46:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTextNode":1:{s:4:"text";s:278:"(for example, the "administer filters" and "bypass node access"
permissions provided by Drupal core). When set to TRUE, a standard
warning message defined in user_admin_permissions() will be displayed
with the permission on the permission administration page. Defaults
to FALSE.";}i:8;O:46:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTextNode":1:{s:4:"text";s:478:"- warning: (optional) A translated warning message to display for this
permission on the permission administration page. This warning
overrides the automatic warning generated by \'restrict access\' being
set to TRUE. This should rarely be used, since it is important for all
permissions to have a clear, consistent security warning that is the
same across the site. Use the \'description\' key instead to provide any
information that is specific to the permission you are defining.";}i:9;O:46:"PHPStan\\PhpDocParser\\Ast\\PhpDoc\\PhpDocTextNode":1:{s:4:"text";s:59:"- provider: (optional) The provider name of the permission.";}}}',
));